### ISSUE TITLE
Uncaught TYPO3 Exception by use of category marker

### ISSUE THREAD

**Issue by whazzz** [nimius/location-manager#2]
Hey guys, 
If i use the option for custom marker images in categories, i get the following Uncaught TYPO3 Exception in the frontend:

Uncaught TYPO3 Exception
Call to a member function isEnvironmentInFrontendMode() on null 

Error thrown in file
/html/typo3/typo3_src-8.7.3/typo3/sysext/extbase/Classes/Service/ImageService.php in line 172.

This appears after I saved the image for the marker in the sys_category and assigned the category to a Location.
In the system protocol i get the message Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function isEnvironmentInFrontendMode() on null | Error thrown in file /html/typo3/typo3_src-8.7.3/typo3/sysext/extbase/Classes/Service/ImageService.php in line 172.

**Comment by medismedia** [comment]
I got the same problem. Typo3 7.6.18  & 7.6.21

**Comment by lochmueller** [comment]
Hey guys... the problem is the create process of the ImageService. GeneralUtility is not enough, if the target object use DI. Patch attached...

[local_history.txt](https://github.com/nimius/location-manager/files/1240039/local_history.txt)

**Comment by jrenggli** [comment]
@lochmueller: Thanks for your patch. It just helped me fix the same bug in another extension.

Maybe you could try writing a pull request so this bug would be fixed here as well.
